import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const store = {};
globalThis.localStorage = { getItem: (k) => (k in store ? store[k] : null), setItem: (k, v) => { store[k] = String(v); }, removeItem: (k) => { delete store[k]; } };
globalThis.window = { dispatchEvent() {} }; globalThis.CustomEvent = class { constructor(n) { this.type = n; } };
const m = await import(path.join(root, 'frontend/src/data/legalTemplates.js'));
let n = 0; const ok = (a, c, x = '') => { if (!c) { console.error('FAIL', a, x); process.exit(1); } n++; console.log('ok  ', a); };
const base = m.TEMPLATES.length;
const r = m.saveCustomTemplate({ title: 'Bail draft - Ravi - 2026-09-29', text: 'IN THE [Court / Forum]\n\nRavi, r/o [address]\n\nDate: [Date]\n\n[Court / Forum] again [verify: x]' });
ok('saved', r.ok && r.fields === 3, JSON.stringify(r));
ok('template appended', m.TEMPLATES.length === base + 1 && m.TEMPLATES.at(-1).category === 'My Saved Forms');
ok('category added', m.CATEGORIES.includes('My Saved Forms'));
const t = m.TEMPLATES.at(-1);
ok('placeholders became fields (same label = same key)', t.preview.split('{{court_forum}}').length === 3 && t.fields.map((f) => f.type).join() === 'text,textarea,date', t.preview + JSON.stringify(t.fields));
ok('verify tag preserved, not a field', t.preview.includes('[verify: x]'));
ok('html_template built', t.html_template.startsWith('<p>') && t.schema.length === 3);
const r2 = m.saveCustomTemplate({ title: 'Bail draft - Ravi - 2026-09-29', text: 'v2 [Name]' });
ok('same title replaces', r2.replaced && m.TEMPLATES.length === base + 1 && m.TEMPLATES.at(-1).preview === 'v2 {{name}}');
ok('delete', m.deleteCustomTemplate(r2.id) && m.TEMPLATES.length === base && !m.CATEGORIES.includes('My Saved Forms'));
console.log(`ALL ${n} CHECKS PASSED`);
